const API='https://script.google.com/macros/s/AKfycbzx_y12qFOfQ9uc9_5gfuHGbCw_JV2gwU1MGFnIgDnOuQ6lNhgw9hyMrYk8-Xv9oqDP/exec';
const app=document.getElementById('app');
const pages={home:()=>`<div class="app"><header class="top"><img src="logo.jpg" class="logo"><div><div class="brand">Mein Haus</div><div class="muted">Shtëpia Ime</div></div><button class="avatar" onclick="go('profile')">IS</button></header><main class="page"><div class="hello">Mirë se vini, Ilaz</div><p class="lead">Ja një përmbledhje e shtëpisë tuaj.</p><div class="grid"><button class="tile blue" onclick="go('family')"><span class="ico">👥</span><b>Familja</b><small>Anëtarët</small></button><button class="tile red" onclick="go('appointments')"><span class="ico">📅</span><b>Terminat</b><small>Terminat e ardhshme</small></button><button class="tile green" onclick="go('shopping')"><span class="ico">🛒</span><b>Lista e blerjeve</b><small>Lista aktive</small></button><button class="tile orange" onclick="go('offers')"><span class="ico">🏷️</span><b>Ofertat</b><small>Oferta aktive</small></button></div><div class="card info"><b>☀️ Sot në Frankenthal</b><div>Familja, terminet dhe blerjet në një vend.</div></div></main>${nav('home')}</div>`,
family:()=>screen('Familja','<div id="familyList" class="list"></div><button class="primary">＋ Shto anëtar</button>','family'),
appointments:()=>screen('Terminat','<div class="card" style="padding:16px"><b>Tetor 2026</b><p class="muted">Kalendari familjar</p></div><h3>Terminat e ardhshme</h3><div id="appointmentList" class="list"></div>','appointments'),
shopping:()=>screen('Lista e blerjeve','<input class="input" placeholder="Kërko në listë…"><div class="chips"><button class="chip on">Të gjitha</button><button class="chip">Ushqime</button><button class="chip">Pije</button><button class="chip">Shtëpi</button></div><div id="shoppingList" class="list"></div>','shopping'),
offers:()=>screen('Ofertat','<input class="input" placeholder="Kërko oferta…"><div id="offersList" class="grid"></div>','offers'),
profile:()=>screen('Profili','<div class="card" style="padding:18px"><b>Ilaz</b><p class="muted">Profili i familjes</p></div>','profile')};
function nav(on){return `<nav class="bottom">${[['home','⌂','Ballina'],['family','👥','Familja'],['appointments','📅','Terminat'],['shopping','🛒','Blerjet'],['offers','🏷️','Ofertat']].map(x=>`<button class="nav ${on===x[0]?'on':''}" onclick="go('${x[0]}')"><span>${x[1]}</span>${x[2]}</button>`).join('')}</nav>`}
function screen(title,body,on){return `<div class="app"><header class="top"><img src="logo.jpg" class="logo"><div><div class="brand">Mein Haus</div><div class="muted">Shtëpia Ime</div></div></header><main class="page"><div class="pagehead"><button class="back" onclick="go('home')">‹</button><h2>${title}</h2><button class="add">＋</button></div>${body}</main>${nav(on)}</div>`}
function go(p){app.innerHTML=(pages[p]||pages.home)();location.hash=p}
go(location.hash.slice(1)||'home');