const API='https://script.google.com/macros/s/AKfycbzx_y12qFOfQ9uc9_5gfuHGbCw_JV2gwU1MGFnIgDnOuQ6lNhgw9hyMrYk8-Xv9oqDP/exec';
const app=document.getElementById('app');
const state={me:null,family:[],appointments:[],shopping:[],offers:[]};let offerStore='';
async function api(action,payload={}){const body={action,...payload};const token=localStorage.getItem('mh_token');if(token)body.token=token;const r=await fetch(API,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(body),redirect:'follow'});const raw=await r.text();let j;try{j=JSON.parse(raw)}catch(e){throw Error('Serveri nuk ktheu JSON. Kontrollo deployment-in e Apps Script.')}if(!j.ok)throw Error(j.error||'Gabim');return j.data}
function loginView(msg=''){app.innerHTML=`<div class="app login"><h1>Mein Haus</h1><p>Shtëpia Ime</p><div class="card"><b>Hyr / Anmelden</b><input id="email" class="input" type="email" placeholder="Email"><input id="pass" class="input" type="password" placeholder="Fjalëkalimi"><button class="primary" onclick="login()">Anmelden</button><div class="muted" style="margin-top:10px">${msg}</div></div></div>`}
async function login(){try{const email=document.getElementById('email').value.trim(),password=document.getElementById('pass').value;const d=await api('login',{email,password,device:'BUILD1'});localStorage.setItem('mh_token',d.token);state.me=d.user||{};go('home');loadPageData('home')}catch(e){loginView(e.message)}}
async function boot(){const t=localStorage.getItem('mh_token');if(!t)return loginView();try{state.me=await api('sessionCheck');go(location.hash.slice(1)||'home');loadPageData(location.hash.slice(1)||'home')}catch(e){localStorage.removeItem('mh_token');loginView('Kyçu përsëri.')}}
async function loadPageData(p){try{if(p==='family'){state.family=await api('family');renderCards('familyList',state.family,x=>x.displayName||[x.firstName,x.lastName].filter(Boolean).join(' '),x=>x.relation||'Familja')}if(p==='appointments'){state.appointments=await api('appointmentList');renderCards('appointmentList',Array.isArray(state.appointments)?state.appointments:(state.appointments.items||[]),x=>x.title||[x.firstName,x.lastName].filter(Boolean).join(' ')||'Termin',x=>[x.date,x.time,x.location].filter(Boolean).join(' • '))}if(p==='shopping'){const d=await api('shoppingList');state.shopping=Array.isArray(d)?d:(d.items||[]);renderCards('shoppingList',state.shopping,x=>x.Produkti||x.product||'Produkt',x=>[(x.Sasia||x.quantity||''),(x['Njësia']||x.unit||''),x.Kategoria||x.category||''].filter(Boolean).join(' ') )}if(p==='offers'){const d=await api('offersList',{country:'DE',city:'Frankenthal'});state.offers=Array.isArray(d)?d:(d.items||d.offers||[]);renderOffers()}if(p==='profile'){const n=document.getElementById('profileName'),m=document.getElementById('profileMail');if(n)n.textContent=state.me?.displayName||'Profili';if(m)m.textContent=state.me?.email||''}}catch(e){const el=document.querySelector('.list');if(el)el.innerHTML=`<div class="card">${e.message}</div>`}}
function renderCards(id,arr,title,sub){const el=document.getElementById(id);if(!el)return;el.innerHTML=arr.length?arr.map(x=>`<div class="card"><b>${esc(title(x))}</b><div class="muted">${esc(sub(x)||'')}</div></div>`).join(''):'<div class="card"><span class="muted">Nuk ka të dhëna.</span></div>'}
function esc(s){return String(s??'').replace(/[&<>"']/g,a=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[a]))}
const pages={home:()=>`<div class="app"><header class="top"><img src="logo.jpg" class="logo"><div><div class="brand">Mein Haus</div><div class="muted">Shtëpia Ime</div></div><button class="avatar" onclick="go('profile')">IS</button></header><main class="page"><div class="hello">Mirë se vini, Ilaz</div><p class="lead">Ja një përmbledhje e shtëpisë tuaj.</p><div class="grid"><button class="tile blue" onclick="go('family')"><span class="ico">👥</span><b>Familja</b><small>Anëtarët</small></button><button class="tile red" onclick="go('appointments')"><span class="ico">📅</span><b>Terminat</b><small>Terminat e ardhshme</small></button><button class="tile green" onclick="go('shopping')"><span class="ico">🛒</span><b>Lista e blerjeve</b><small>Lista aktive</small></button><button class="tile orange" onclick="go('offers')"><span class="ico">🏷️</span><b>Ofertat</b><small>Oferta aktive</small></button></div><div class="card info"><b>☀️ Sot në Frankenthal</b><div>Familja, terminet dhe blerjet në një vend.</div></div></main>${nav('home')}</div>`,
family:()=>screen('Familja','<div id="familyList" class="list"></div><button class="primary" onclick="memberForm()">＋ Shto anëtar</button><div id="memberForm"></div>','family'),
appointments:()=>screen('Terminat','<div class="card" style="padding:16px"><b>Tetor 2026</b><p class="muted">Kalendari familjar</p></div><h3>Terminat e ardhshme</h3><div id="appointmentList" class="list"></div><button class="primary" onclick="appointmentForm()">＋ Shto termin</button><div id="appointmentForm"></div>','appointments'),
shopping:()=>screen('Lista e blerjeve','<input class="input" placeholder="Kërko në listë…"><div class="chips"><button class="chip on">Të gjitha</button><button class="chip">Ushqime</button><button class="chip">Pije</button><button class="chip">Shtëpi</button></div><div id="shoppingList" class="list"></div><button class="primary" onclick="shoppingForm()">＋ Shto produkt</button><div id="shoppingForm"></div>','shopping'),
offers:()=>screen('Ofertat','<input id="offerQ" class="input" placeholder="Kërko oferta…" oninput="renderOffers()"><div class="chips"><button class="chip on" onclick="offerStore=\'\';renderOffers()">Të gjitha</button><button class="chip" onclick="offerStore=\'Lidl\';renderOffers()">Lidl</button><button class="chip" onclick="offerStore=\'ALDI\';renderOffers()">ALDI</button><button class="chip" onclick="offerStore=\'REWE\';renderOffers()">REWE</button><button class="chip" onclick="offerStore=\'Kaufland\';renderOffers()">Kaufland</button></div><div id="offersList" class="grid"></div>','offers'),
profile:()=>screen('Profili','<div class="profileHero card"><div class="profileAvatar">IS</div><b id="profileName">Profili</b><p class="muted" id="profileMail"></p></div><div class="card profileRow" onclick="toggleTheme()"><span>◐</span><div><b>Pamja</b><div class="muted">Dritë / Errët</div></div><strong>›</strong></div><div class="card profileRow"><span>🌐</span><div><b>Gjuha</b><div class="muted">Shqip / Deutsch</div></div><strong>›</strong></div><button class="logout" onclick="logout()">Dil nga llogaria</button>','profile')};
function nav(on){return `<nav class="bottom">${[['home','⌂','Ballina'],['family','👥','Familja'],['appointments','📅','Terminat'],['shopping','🛒','Blerjet'],['offers','🏷️','Ofertat']].map(x=>`<button class="nav ${on===x[0]?'on':''}" onclick="go('${x[0]}')"><span>${x[1]}</span>${x[2]}</button>`).join('')}</nav>`}
function screen(title,body,on){return `<div class="app"><header class="top"><img src="logo.jpg" class="logo"><div><div class="brand">Mein Haus</div><div class="muted">Shtëpia Ime</div></div></header><main class="page"><div class="pagehead"><button class="back" onclick="go('home')">‹</button><h2>${title}</h2><button class="add">＋</button></div>${body}</main>${nav(on)}</div>`}
function go(p){app.innerHTML=(pages[p]||pages.home)();location.hash=p;loadPageData(p)}
boot();
function memberForm(){document.getElementById('memberForm').innerHTML='<div class="card" style="padding:14px;margin-top:10px"><input id="mf" class="input" placeholder="Emri"><input id="ml" class="input" placeholder="Mbiemri"><input id="mr" class="input" placeholder="Lidhja familjare"><button class="primary" onclick="saveMember()">Ruaj</button></div>'}
async function saveMember(){try{await api('familyMemberSave',{firstName:mf.value.trim(),lastName:ml.value.trim(),relation:mr.value.trim()});go('family')}catch(e){alert(e.message)}}
function appointmentForm(){document.getElementById('appointmentForm').innerHTML='<div class="card" style="padding:14px;margin-top:10px"><input id="at" class="input" placeholder="Titulli"><input id="ad" class="input" type="date"><input id="ati" class="input" type="time"><input id="al" class="input" placeholder="Vendi"><button class="primary" onclick="saveAppointment()">Ruaj terminin</button></div>'}
async function saveAppointment(){try{await api('appointmentSave',{title:at.value.trim(),date:ad.value,time:ati.value,location:al.value,status:'active'});go('appointments')}catch(e){alert(e.message)}}
function shoppingForm(){document.getElementById('shoppingForm').innerHTML='<div class="card" style="padding:14px;margin-top:10px"><input id="sp" class="input" placeholder="Produkti"><input id="sq" class="input" type="number" value="1" min="1"><input id="sc" class="input" placeholder="Kategoria"><button class="primary" onclick="saveShopping()">Shto në listë</button></div>'}
async function saveShopping(){try{await api('shoppingAdd',{product:sp.value.trim(),quantity:Number(sq.value||1),category:sc.value.trim()});go('shopping')}catch(e){alert(e.message)}}
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));

function renderOffers(){const el=document.getElementById('offersList');if(!el)return;const q=(document.getElementById('offerQ')?.value||'').toLowerCase();const a=state.offers.filter(x=>(!offerStore||String(x.store||'').toLowerCase().includes(offerStore.toLowerCase()))&&(!q||String(x.product||x.Produkti||'').toLowerCase().includes(q)));el.innerHTML=a.length?a.map(x=>'<div class="offerCard card">'+(x.imageUrl?'<img src="'+esc(x.imageUrl)+'" loading="lazy">':'<div class="offerPh">🏷️</div>')+'<small>'+esc(x.store||'')+'</small><b>'+esc(x.product||x.Produkti||'Ofertë')+'</b><div class="offerPrice">'+esc(x.price||'')+(x.price?' €':'')+'</div></div>').join(''):'<div class="card" style="padding:14px;grid-column:1/-1"><span class="muted">Nuk ka oferta aktive.</span></div>'}
function toggleTheme(){document.documentElement.classList.toggle('dark');localStorage.setItem('mh_theme',document.documentElement.classList.contains('dark')?'dark':'light')}
function logout(){localStorage.removeItem('mh_token');state.me=null;loginView()}
if(localStorage.getItem('mh_theme')==='dark')document.documentElement.classList.add('dark');
