const API='https://script.google.com/macros/s/AKfycbzx_y12qFOfQ9uc9_5gfuHGbCw_JV2gwU1MGFnIgDnOuQ6lNhgw9hyMrYk8-Xv9oqDP/exec';
const app=document.getElementById('app');
const state={me:null,family:[],appointments:[],shopping:[]};
async function api(action,payload={}){const body={action,...payload};const token=localStorage.getItem('mh_token');if(token)body.token=token;const r=await fetch(API,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(body)});const j=await r.json();if(!j.ok)throw Error(j.error||'Gabim');return j.data}
function loginView(msg=''){app.innerHTML=`<div class="app login"><h1>Mein Haus</h1><p>Shtëpia Ime</p><div class="card"><b>Hyr / Anmelden</b><input id="email" class="input" type="email" placeholder="Email"><input id="pass" class="input" type="password" placeholder="Fjalëkalimi"><button class="primary" onclick="login()">Anmelden</button><div class="muted" style="margin-top:10px">${msg}</div></div></div>`}
async function login(){try{const email=document.getElementById('email').value.trim(),password=document.getElementById('pass').value;const d=await api('login',{email,password,device:'BUILD1'});localStorage.setItem('mh_token',d.token);state.me=d.user||{};go('home');loadPageData('home')}catch(e){loginView(e.message)}}
async function boot(){const t=localStorage.getItem('mh_token');if(!t)return loginView();try{state.me=await api('sessionCheck');go(location.hash.slice(1)||'home');loadPageData(location.hash.slice(1)||'home')}catch(e){localStorage.removeItem('mh_token');loginView('Kyçu përsëri.')}}
async function loadPageData(p){try{if(p==='family'){state.family=await api('family');renderCards('familyList',state.family,x=>x.displayName||[x.firstName,x.lastName].filter(Boolean).join(' '),x=>x.relation||'Familja')}if(p==='appointments'){state.appointments=await api('appointmentList');renderCards('appointmentList',Array.isArray(state.appointments)?state.appointments:(state.appointments.items||[]),x=>x.title||[x.firstName,x.lastName].filter(Boolean).join(' ')||'Termin',x=>[x.date,x.time,x.location].filter(Boolean).join(' • '))}if(p==='shopping'){const d=await api('shoppingList');state.shopping=Array.isArray(d)?d:(d.items||[]);renderCards('shoppingList',state.shopping,x=>x.Produkti||x.product||'Produkt',x=>[(x.Sasia||x.quantity||''),(x['Njësia']||x.unit||''),x.Kategoria||x.category||''].filter(Boolean).join(' ') )}}catch(e){const el=document.querySelector('.list');if(el)el.innerHTML=`<div class="card">${e.message}</div>`}}
function renderCards(id,arr,title,sub){const el=document.getElementById(id);if(!el)return;el.innerHTML=arr.length?arr.map(x=>`<div class="card"><b>${esc(title(x))}</b><div class="muted">${esc(sub(x)||'')}</div></div>`).join(''):'<div class="card"><span class="muted">Nuk ka të dhëna.</span></div>'}
function esc(s){return String(s??'').replace(/[&<>"']/g,a=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[a]))}
const pages={home:()=>`<div class="app"><header class="top"><img src="logo.jpg" class="logo"><div><div class="brand">Mein Haus</div><div class="muted">Shtëpia Ime</div></div><button class="avatar" onclick="go('profile')">IS</button></header><main class="page"><div class="hello">Mirë se vini, Ilaz</div><p class="lead">Ja një përmbledhje e shtëpisë tuaj.</p><div class="grid"><button class="tile blue" onclick="go('family')"><span class="ico">👥</span><b>Familja</b><small>Anëtarët</small></button><button class="tile red" onclick="go('appointments')"><span class="ico">📅</span><b>Terminat</b><small>Terminat e ardhshme</small></button><button class="tile green" onclick="go('shopping')"><span class="ico">🛒</span><b>Lista e blerjeve</b><small>Lista aktive</small></button><button class="tile orange" onclick="go('offers')"><span class="ico">🏷️</span><b>Ofertat</b><small>Oferta aktive</small></button></div><div class="card info"><b>☀️ Sot në Frankenthal</b><div>Familja, terminet dhe blerjet në një vend.</div></div></main>${nav('home')}</div>`,
family:()=>screen('Familja','<div id="familyList" class="list"></div><button class="primary">＋ Shto anëtar</button>','family'),
appointments:()=>screen('Terminat','<div class="card" style="padding:16px"><b>Tetor 2026</b><p class="muted">Kalendari familjar</p></div><h3>Terminat e ardhshme</h3><div id="appointmentList" class="list"></div>','appointments'),
shopping:()=>screen('Lista e blerjeve','<input class="input" placeholder="Kërko në listë…"><div class="chips"><button class="chip on">Të gjitha</button><button class="chip">Ushqime</button><button class="chip">Pije</button><button class="chip">Shtëpi</button></div><div id="shoppingList" class="list"></div>','shopping'),
offers:()=>screen('Ofertat','<input class="input" placeholder="Kërko oferta…"><div id="offersList" class="grid"></div>','offers'),
profile:()=>screen('Profili','<div class="card" style="padding:18px"><b>Ilaz</b><p class="muted">Profili i familjes</p></div>','profile')};
function nav(on){return `<nav class="bottom">${[['home','⌂','Ballina'],['family','👥','Familja'],['appointments','📅','Terminat'],['shopping','🛒','Blerjet'],['offers','🏷️','Ofertat']].map(x=>`<button class="nav ${on===x[0]?'on':''}" onclick="go('${x[0]}')"><span>${x[1]}</span>${x[2]}</button>`).join('')}</nav>`}
function screen(title,body,on){return `<div class="app"><header class="top"><img src="logo.jpg" class="logo"><div><div class="brand">Mein Haus</div><div class="muted">Shtëpia Ime</div></div></header><main class="page"><div class="pagehead"><button class="back" onclick="go('home')">‹</button><h2>${title}</h2><button class="add">＋</button></div>${body}</main>${nav(on)}</div>`}
function go(p){app.innerHTML=(pages[p]||pages.home)();location.hash=p;loadPageData(p)}
boot();